function byId<T extends HTMLElement>(id: string): T | null {
  return document.getElementById(id) as T | null;
}

export const elements = {
  fileInput: byId<HTMLInputElement>('file-input'),
  btnLoad: byId<HTMLButtonElement>('btn-load-file'),
  btnViewGrid: byId<HTMLButtonElement>('btn-view-grid'),
  btnGraphConfig: byId<HTMLButtonElement>('btn-graph-config'),
  btnExport: byId<HTMLButtonElement>('btn-export'),
  btnHelp: byId<HTMLButtonElement>('btn-help'),
  btnThemeToggle: byId<HTMLButtonElement>('btn-theme-toggle'),
  btnSidebarToggle: byId<HTMLButtonElement>('btn-sidebar-toggle'),
  sidebar: byId<HTMLElement>('app-sidebar'),
  sidebarBackdrop: byId<HTMLElement>('sidebar-backdrop'),

  pipelinePanel: byId<HTMLElement>('pipeline-panel'),
  pipelineList: byId<HTMLElement>('pipeline-list'),
  pipelineActions: document.querySelector<HTMLElement>('.pipeline-actions'),
  mathTraceNote: byId<HTMLElement>('math-trace-note'),
  btnAddStep: byId<HTMLButtonElement>('btn-add-step'),
  btnRemoveStep: byId<HTMLButtonElement>('btn-remove-step'),
  btnMoveUp: byId<HTMLButtonElement>('btn-move-up'),
  btnMoveDown: byId<HTMLButtonElement>('btn-move-down'),

  paramPanel: byId<HTMLElement>('param-editor'),
  filterTypeDisplay: byId<HTMLElement>('step-type-display'),

  inputWindow: byId<HTMLInputElement>('param-window'),
  inputPoly: byId<HTMLInputElement>('param-poly'),
  inputAlpha: byId<HTMLInputElement>('param-alpha'),
  inputSigma: byId<HTMLInputElement>('param-sigma'),
  inputIters: byId<HTMLInputElement>('param-iters'),
  inputStartDecay: byId<HTMLInputElement>('param-start-decay'),
  inputEndDecay: byId<HTMLInputElement>('param-end-decay'),
  chkApplyStart: byId<HTMLInputElement>('param-apply-start'),
  chkApplyEnd: byId<HTMLInputElement>('param-apply-end'),
  inputStartOffset: byId<HTMLInputElement>('param-start-offset'),
  inputAutoOffsetPoints: byId<HTMLInputElement>('param-offset-points'),
  chkAutoOffset: byId<HTMLInputElement>('param-auto-offset'),
  inputFreq: byId<HTMLInputElement>('param-freq'),
  selFreqUnit: byId<HTMLSelectElement>('unit-freq'),
  inputSlope: byId<HTMLInputElement>('param-slope'),
  inputQ: byId<HTMLInputElement>('param-q'),
  inputBW: byId<HTMLInputElement>('param-bw'),
  selBWUnit: byId<HTMLSelectElement>('unit-bw'),

  sliderWindow: byId<HTMLInputElement>('slider-window'),
  sliderPoly: byId<HTMLInputElement>('slider-poly'),
  sliderAlpha: byId<HTMLInputElement>('slider-alpha'),
  sliderSigma: byId<HTMLInputElement>('slider-sigma'),
  sliderIters: byId<HTMLInputElement>('slider-iters'),
  sliderStartDecay: byId<HTMLInputElement>('slider-start-decay'),
  sliderEndDecay: byId<HTMLInputElement>('slider-end-decay'),
  sliderSlope: byId<HTMLInputElement>('slider-slope'),
  sliderQ: byId<HTMLInputElement>('slider-q'),

  grpWindow: byId<HTMLElement>('group-window'),
  grpPoly: byId<HTMLElement>('group-poly'),
  grpAlpha: byId<HTMLElement>('group-alpha'),
  grpSigma: byId<HTMLElement>('group-sigma'),
  grpIters: byId<HTMLElement>('group-iters'),
  grpDecay: byId<HTMLElement>('group-decay'),
  grpFreq: byId<HTMLElement>('group-freq'),
  grpSlope: byId<HTMLElement>('group-slope'),
  grpQ: byId<HTMLElement>('group-q'),
  grpBW: byId<HTMLElement>('group-bw'),

  liveShowRaw: byId<HTMLInputElement>('live-show-raw'),
  liveRawOpacity: byId<HTMLInputElement>('live-raw-opacity'),
  liveShowDiff: byId<HTMLInputElement>('live-show-diff'),
  liveViewMode: byId<HTMLSelectElement>('live-view-mode'),
  liveShowEvents: byId<HTMLInputElement>('live-show-events'),
  liveStatus: byId<HTMLElement>('live-status'),
  diffGroup: byId<HTMLElement>('tool-group-diff'),

  tabContainer: byId<HTMLElement>('column-tabs'),
  tabViewport: byId<HTMLElement>('tabs-scroll-viewport'),
  tabsWrapper: byId<HTMLElement>('tabs-wrapper'),
  tabsScrollbar: byId<HTMLElement>('tabs-scrollbar'),
  tabsScrollbarSpacer: byId<HTMLElement>('tabs-scrollbar-spacer'),
  btnAddMultiView: byId<HTMLButtonElement>('btn-add-multiview'),
  chkSyncTabs: byId<HTMLInputElement>('chk-sync-tabs'),
  traceSelectorPanel: byId<HTMLElement>('trace-selector-panel'),
  traceSelectorList: byId<HTMLElement>('trace-selector-list'),

  composerPanel: byId<HTMLElement>('composer-panel'),
  composerList: byId<HTMLElement>('composer-list')
};
