export const elements = {
    fileInput: document.getElementById('file-input'),
    btnLoad: document.getElementById('btn-load-file'),
    btnViewGrid: document.getElementById('btn-view-grid'),
    btnGraphConfig: document.getElementById('btn-graph-config'),
    btnExport: document.getElementById('btn-export'),
    btnHelp: document.getElementById('btn-help'),
    btnThemeToggle: document.getElementById('btn-theme-toggle'),

    pipelineList: document.getElementById('pipeline-list'),
    pipelineActions: document.querySelector('.pipeline-actions'),
    mathTraceNote: document.getElementById('math-trace-note'),
    btnAddStep: document.getElementById('btn-add-step'),
    btnRemoveStep: document.getElementById('btn-remove-step'),
    btnMoveUp: document.getElementById('btn-move-up'),
    btnMoveDown: document.getElementById('btn-move-down'),

    paramPanel: document.getElementById('param-editor'),
    filterTypeDisplay: document.getElementById('step-type-display'),

    inputWindow: document.getElementById('param-window'),
    inputPoly: document.getElementById('param-poly'),
    inputAlpha: document.getElementById('param-alpha'),
    inputSigma: document.getElementById('param-sigma'),
    inputIters: document.getElementById('param-iters'),
    inputStartDecay: document.getElementById('param-start-decay'),
    inputEndDecay: document.getElementById('param-end-decay'),
    chkApplyStart: document.getElementById('param-apply-start'),
    chkApplyEnd: document.getElementById('param-apply-end'),
    inputStartOffset: document.getElementById('param-start-offset'),
    inputAutoOffsetPoints: document.getElementById('param-offset-points'),
    chkAutoOffset: document.getElementById('param-auto-offset'),
    inputFreq: document.getElementById('param-freq'),
    selFreqUnit: document.getElementById('unit-freq'),
    inputSlope: document.getElementById('param-slope'),
    inputQ: document.getElementById('param-q'),
    inputBW: document.getElementById('param-bw'),
    selBWUnit: document.getElementById('unit-bw'),

    sliderWindow: document.getElementById('slider-window'),
    sliderPoly: document.getElementById('slider-poly'),
    sliderAlpha: document.getElementById('slider-alpha'),
    sliderSigma: document.getElementById('slider-sigma'),
    sliderIters: document.getElementById('slider-iters'),
    sliderStartDecay: document.getElementById('slider-start-decay'),
    sliderEndDecay: document.getElementById('slider-end-decay'),
    sliderSlope: document.getElementById('slider-slope'),
    sliderQ: document.getElementById('slider-q'),

    grpWindow: document.getElementById('group-window'),
    grpPoly: document.getElementById('group-poly'),
    grpAlpha: document.getElementById('group-alpha'),
    grpSigma: document.getElementById('group-sigma'),
    grpIters: document.getElementById('group-iters'),
    grpDecay: document.getElementById('group-decay'),
    grpFreq: document.getElementById('group-freq'),
    grpSlope: document.getElementById('group-slope'),
    grpQ: document.getElementById('group-q'),
    grpBW: document.getElementById('group-bw'),

    liveShowRaw: document.getElementById('live-show-raw'),
    liveRawOpacity: document.getElementById('live-raw-opacity'),
    liveShowDiff: document.getElementById('live-show-diff'),
    liveViewMode: document.getElementById('live-view-mode'),
    liveShowEvents: document.getElementById('live-show-events'),
    liveStatus: document.getElementById('live-status'),

    eventPanel: document.getElementById('events-panel'),
    eventType: document.getElementById('event-type'),
    eventDirection: document.getElementById('event-direction'),
    eventThreshold: document.getElementById('event-threshold'),
    eventHysteresis: document.getElementById('event-hysteresis'),
    eventSlope: document.getElementById('event-slope'),
    eventMinWidth: document.getElementById('event-min-width'),
    eventMaxWidth: document.getElementById('event-max-width'),
    eventHighThreshold: document.getElementById('event-high-threshold'),
    eventLowThreshold: document.getElementById('event-low-threshold'),
    eventSource: document.getElementById('event-source'),
    eventUseSelection: document.getElementById('event-use-selection'),
    eventList: document.getElementById('event-list'),
    eventCount: document.getElementById('event-count'),
    btnEventPrev: document.getElementById('btn-event-prev'),
    btnEventNext: document.getElementById('btn-event-next'),

    measurementPanel: document.getElementById('measurement-panel'),
    measurementPreset: document.getElementById('measurement-preset'),
    measurementRows: document.getElementById('measurement-rows'),

    spectralPanel: document.getElementById('spectral-panel'),
    fftWindow: document.getElementById('fft-window'),
    fftDetrend: document.getElementById('fft-detrend'),
    fftZeroPad: document.getElementById('fft-zero-pad'),
    fftZeroFactor: document.getElementById('fft-zero-factor'),
    fftView: document.getElementById('fft-view'),
    fftSource: document.getElementById('fft-source'),
    fftPeakCount: document.getElementById('fft-peak-count'),
    fftPeakProminence: document.getElementById('fft-peak-prominence'),
    fftShowHarmonics: document.getElementById('fft-show-harmonics'),
    fftHarmonicCount: document.getElementById('fft-harmonic-count'),
    fftFundamental: document.getElementById('fft-fundamental'),

    systemPanel: document.getElementById('system-panel'),
    systemInput: document.getElementById('system-input'),
    systemOutput: document.getElementById('system-output'),
    systemUseSelection: document.getElementById('system-use-selection'),
    systemMaxLag: document.getElementById('system-max-lag'),
    systemSummary: document.getElementById('system-summary'),
    systemWarnings: document.getElementById('system-warnings'),

    tabContainer: document.getElementById('column-tabs'),
    tabViewport: document.getElementById('tabs-scroll-viewport'),
    tabsWrapper: document.getElementById('tabs-wrapper'),
    tabsScrollbar: document.getElementById('tabs-scrollbar'),
    tabsScrollbarSpacer: document.getElementById('tabs-scrollbar-spacer'),
    btnAddMultiView: document.getElementById('btn-add-multiview'),
    chkSyncTabs: document.getElementById('chk-sync-tabs'),
    traceSelectorPanel: document.getElementById('trace-selector-panel'),
    traceSelectorList: document.getElementById('trace-selector-list'),

    composerPanel: document.getElementById('composer-panel'),
    composerList: document.getElementById('composer-list')
};
