export const elements = {
    fileInput: document.getElementById('file-input'),
    btnLoad: document.getElementById('btn-load-file'),
    btnViewGrid: document.getElementById('btn-view-grid'),
    btnReferenceGrid: document.getElementById('btn-reference-grid'),
    btnGraphConfig: document.getElementById('btn-graph-config'),
    btnExport: document.getElementById('btn-export'),
    btnHelp: document.getElementById('btn-help'),
    btnThemeToggle: document.getElementById('btn-theme-toggle'),

    pipelineList: document.getElementById('pipeline-list'),
    btnAddStep: document.getElementById('btn-add-step'),
    btnRemoveStep: document.getElementById('btn-remove-step'),
    btnMoveUp: document.getElementById('btn-move-up'),
    btnMoveDown: document.getElementById('btn-move-down'),

    paramPanel: document.getElementById('param-editor'),
    filterTypeDisplay: document.getElementById('step-type-display'),

    inputWindow: document.getElementById('param-window'),
    inputPoly: document.getElementById('param-poly'),
    inputAlpha: document.getElementById('param-alpha'),
    inputSigma: document.getElementById('param-sigma'),
    inputIters: document.getElementById('param-iters'),
    inputStartDecay: document.getElementById('param-start-decay'),
    inputEndDecay: document.getElementById('param-end-decay'),
    chkApplyStart: document.getElementById('param-apply-start'),
    chkApplyEnd: document.getElementById('param-apply-end'),
    inputStartOffset: document.getElementById('param-start-offset'),
    inputAutoOffsetPoints: document.getElementById('param-offset-points'),
    chkAutoOffset: document.getElementById('param-auto-offset'),
    inputFreq: document.getElementById('param-freq'),
    selFreqUnit: document.getElementById('unit-freq'),
    inputSlope: document.getElementById('param-slope'),
    inputQ: document.getElementById('param-q'),
    inputBW: document.getElementById('param-bw'),
    selBWUnit: document.getElementById('unit-bw'),

    sliderWindow: document.getElementById('slider-window'),
    sliderPoly: document.getElementById('slider-poly'),
    sliderAlpha: document.getElementById('slider-alpha'),
    sliderSigma: document.getElementById('slider-sigma'),
    sliderIters: document.getElementById('slider-iters'),
    sliderStartDecay: document.getElementById('slider-start-decay'),
    sliderEndDecay: document.getElementById('slider-end-decay'),
    sliderSlope: document.getElementById('slider-slope'),
    sliderQ: document.getElementById('slider-q'),

    grpWindow: document.getElementById('group-window'),
    grpPoly: document.getElementById('group-poly'),
    grpAlpha: document.getElementById('group-alpha'),
    grpSigma: document.getElementById('group-sigma'),
    grpIters: document.getElementById('group-iters'),
    grpDecay: document.getElementById('group-decay'),
    grpFreq: document.getElementById('group-freq'),
    grpSlope: document.getElementById('group-slope'),
    grpQ: document.getElementById('group-q'),
    grpBW: document.getElementById('group-bw'),

    liveShowRaw: document.getElementById('live-show-raw'),
    liveRawOpacity: document.getElementById('live-raw-opacity'),
    liveShowDiff: document.getElementById('live-show-diff'),
    liveFreqDomain: document.getElementById('live-freq-domain'),
    liveStatus: document.getElementById('live-status'),

    tabContainer: document.getElementById('column-tabs'),
    btnAddMultiView: document.getElementById('btn-add-multiview'),
    chkSyncTabs: document.getElementById('chk-sync-tabs'),
    traceSelectorPanel: document.getElementById('trace-selector-panel'),
    traceSelectorList: document.getElementById('trace-selector-list'),

    composerPanel: document.getElementById('composer-panel'),
    composerList: document.getElementById('composer-list'),

    referencePanel: document.getElementById('reference-panel'),
    referenceList: document.getElementById('reference-list')
};
